// --- Project Types ---
export interface ProjectPhase {
    id: string;
    name: string;
    completed: boolean;
}

export interface Project {
    id: string; // Database PK
    folio?: string; // PROY-2026-... (generated by backend)
    title: string;
    estado: string;
    municipio: string;
    categoria: string;
    tipoEscala: string;
    capas: string[];
    fases: ProjectPhase[];
    avance: number;
    status: 'Completado' | 'En proceso' | 'Pendiente';
}

export interface ProjectFormData {
    title: string;
    estado: string;
    municipio: string;
    categoria: string;
    tipoEscala: string;
    capas: string[];
}

// --- Validation Choices matching Backend ---
export const CATEGORIA_CHOICES = [
    { value: 'ALTIMETRIA', label: 'Altimetría' },
    { value: 'CATASTRO', label: 'Catastro' },
    { value: 'EQUIPAMIENTO', label: 'Equipamiento Urbano' },
    { value: 'ESTRUCTURA', label: 'Estructura Urbana' },
    { value: 'HIDROLOGIA', label: 'Hidrología' },
    { value: 'INFRAESTRUCTURA', label: 'Infraestructura' },
    { value: 'TOPOGRAFIA', label: 'Topografía' },
    { value: 'USOS_PREDIO', label: 'Usos de Predio' },
    { value: 'VEGETACION', label: 'Vegetación' },
    { value: 'VIAS', label: 'Vías' },
    { value: 'OTROS', label: 'Otros' },
];

export const ESCALA_CHOICES = [
    { value: '1:500', label: '1:500' },
    { value: '1:1000', label: '1:1,000' },
    { value: '1:2000', label: '1:2,000' },
    { value: '1:5000', label: '1:5,000' },
    { value: '1:10000', label: '1:10,000' },
    { value: '1:20000', label: '1:20,000' },
    { value: '1:50000', label: '1:50,000' },
    { value: 'OTRA', label: 'Otra' },
];

// --- Constants ---
export const AVAILABLE_CAPAS = [
    'Predios',
    'Manzanas',
    'Vialidades',
    'Construcciones',
    'Parcelas',
    'Límites Ejidales',
    'Puntos de Control',
    'Red Geodésica',
    'Hidrografía',
    'Curvas de Nivel',
    'Uso de Suelo',
    'Zonas Urbanas',
    'Áreas Verdes',
    'Infraestructura',
    'Límites Municipales',
    'Otra'
];

export const DEFAULT_PHASES = [
    'Planeación',
    'Levantamiento Topográfico',
    'Digitalización',
    'Control de Calidad',
    'Entrega',
];

export const STATUS_CONFIG: Record<string, { bg: string; text: string; dot: string }> = {
    'Completado': { bg: 'bg-emerald-50', text: 'text-emerald-700', dot: 'bg-emerald-500' },
    'En proceso': { bg: 'bg-amber-50', text: 'text-amber-700', dot: 'bg-amber-500' },
    'Pendiente': { bg: 'bg-slate-100', text: 'text-slate-600', dot: 'bg-slate-400' },
};

export const EMPTY_FORM: ProjectFormData = {
    title: '',
    estado: '',
    municipio: '',
    categoria: '',
    tipoEscala: '',
    capas: [],
};

export const MOCK_PROJECTS: Project[] = [
    {
        id: 'SICAT-2024-001',
        title: 'Zona Norte Hidalgo',
        estado: 'Hidalgo',
        municipio: 'Pachuca de Soto',
        categoria: 'Catastro Urbano',
        tipoEscala: '1:5000',
        capas: ['Predios', 'Manzanas', 'Vialidades'],
        fases: [
            { id: 'f1', name: 'Planeación', completed: true },
            { id: 'f2', name: 'Levantamiento Topográfico', completed: true },
            { id: 'f3', name: 'Digitalización', completed: true },
            { id: 'f4', name: 'Control de Calidad', completed: true },
            { id: 'f5', name: 'Entrega', completed: true },
        ],
        avance: 100,
        status: 'Completado',
    },
    {
        id: 'SICAT-2024-002',
        title: 'Catastro Urbano CDMX',
        estado: 'Ciudad de México',
        municipio: 'Cuauhtémoc',
        categoria: 'Catastro Urbano',
        tipoEscala: '1:2000',
        capas: ['Predios', 'Construcciones'],
        fases: [
            { id: 'f1', name: 'Planeación', completed: true },
            { id: 'f2', name: 'Levantamiento Topográfico', completed: true },
            { id: 'f3', name: 'Digitalización', completed: false },
            { id: 'f4', name: 'Control de Calidad', completed: false },
            { id: 'f5', name: 'Entrega', completed: false },
        ],
        avance: 45,
        status: 'En proceso',
    },
    {
        id: 'SICAT-2024-003',
        title: 'Predios Rurales Sonora',
        estado: 'Sonora',
        municipio: 'Hermosillo',
        categoria: 'Catastro Rural',
        tipoEscala: '1:10000',
        capas: ['Parcelas', 'Límites Ejidales'],
        fases: [
            { id: 'f1', name: 'Planeación', completed: true },
            { id: 'f2', name: 'Levantamiento Topográfico', completed: false },
            { id: 'f3', name: 'Digitalización', completed: false },
            { id: 'f4', name: 'Control de Calidad', completed: false },
            { id: 'f5', name: 'Entrega', completed: false },
        ],
        avance: 20,
        status: 'En proceso',
    },
    {
        id: 'SICAT-2024-004',
        title: 'Levantamiento Jalisco',
        estado: 'Jalisco',
        municipio: 'Guadalajara',
        categoria: 'Levantamiento Topográfico',
        tipoEscala: '1:1000',
        capas: ['Puntos de Control', 'Red Geodésica'],
        fases: [
            { id: 'f1', name: 'Planeación', completed: false },
            { id: 'f2', name: 'Levantamiento Topográfico', completed: false },
            { id: 'f3', name: 'Digitalización', completed: false },
            { id: 'f4', name: 'Control de Calidad', completed: false },
            { id: 'f5', name: 'Entrega', completed: false },
        ],
        avance: 0,
        status: 'Pendiente',
    },
];
